### ISSUE TITLE
cannot display airports layer

### ISSUE THREAD

**Issue by pilotrex** [haoliangyu/ngx-leaflet-starter#35]
Hello,

First of all, thanks for sharing this starter. It's super helpful!

I'm running into an issue when clicking on the airport button:

> Error: Uncaught (in promise): TypeError: Cannot use 'in' operator to search for 'x' in 756
> TypeError: Cannot use 'in' operator to search for 'x' in 756

I've clone the project and ran npm install && npm run build. Am I missing something?

Thanks again and best regards

**Comment by haoliangyu** [comment]
This error message is caused by [Leaflet.VectorGrid]. In its current publish version (v1.2.0), there is a bug ([#32](https://github.com/Leaflet/Leaflet.VectorGrid/issues/32)) in the slicing of point geojson into vector tile layer. Its next release will fix this issue and I believe it's coming soon ([here](https://github.com/Leaflet/Leaflet.VectorGrid/pull/95)).

So you are doing pretty well instead :-)

**Comment by pilotrex** [comment]
Great. Thanks for getting back to me so quickly! I really appreciate it.
