### ISSUE TITLE
how to use leaflet.TileLayer.WMTS plugin

### ISSUE THREAD

**Issue by cdqrain** [haoliangyu/ngx-leaflet-starter#39]
can you give me an example of how to use the wmts plugin? this plugin can be installed from npm. `npm  install leaflet-tilelayer-wmts`.  after installed, how to use it?

**Comment by haoliangyu** [comment]
I don't have a running example for the `leaflet-tilelayer-wmts`, but from my experience of using `leaflet-vectorgrid`, you could do:

1. import the library with `import 'leaflet-tilelayer-wmts';`
2. create a minimal type definition file `leaflet-tilelayer-wmts.d.ts` so that TypeScript can recognize the WMTS function. The type definition file should look like

``` typescript
declare namespace L {
    namespace TileLayer {
        export function WMTS(url: string, options?: any): any;
    }
}
```

Then you need to add this type definition at where the `leaflet-tilelayer-wmts` is used:

``` typescript
/// <reference path="path/to/leaflet-tilelayer-wmts.d.ts"/>
```
3. After finishing step 1 and 2, you should be able to use `L.TileLayer.WMTS` directly.

This is not tested. So if you have met any problem, feel free to comment.
