### ISSUE TITLE
Airport layer not working

### ISSUE THREAD

**Issue by mrinalusp** [haoliangyu/ngx-leaflet-starter#49]
HELLO,

The airport layer is not working

**Comment by haoliangyu** [comment]
@mrinalusp Thank you for reporting this issue. It is fixed now.

**Comment by mrinalusp** [comment]
Thank you!

**Comment by mrinalusp** [comment]
Sorry , did not want to create more issue. so appending here... 

Getting the below when i try to open the component that has the map
AppComponent.html:52 ERROR TypeError: Cannot read property '_leaflet_events' of null
    at addOne (leaflet-src.js:2277)
    at on (leaflet-src.js:2235)
    at Object.disableClickPropagation (leaflet-src.js:2390)
    at MapService.disableMouseEvent (map.service.ts:39)
    at ToolbarComponent.ngOnInit (toolbar.component.ts:27)
    at checkAndUpdateDirectiveInline (core.js:12352)
    at checkAndUpdateNodeInline (core.js:13876)
    at checkAndUpdateNode (core.js:13819)
    at debugCheckAndUpdateNode (core.js:14712)
    at debugCheckDirectivesFn (core.js:14653)

**Comment by haoliangyu** [comment]
What do you mean by `open the component that has the map`?

**Comment by mrinalusp** [comment]
was having some issue with disableMouseEvent . Commented a few lines. Not sure what it does.

Is there a way to change the markers for airport layers? Its coming as circle always. Tried to use vectorTileOptions but it doesnt have any effect.

**Comment by haoliangyu** [comment]
The `disableMouseEvent` is used to prevent the mouse events on the search bar from moving/changing the map. Not sure why it causes the problem here.

I believe leaflet-vectorgrid has implemented the custom icon for point layers. But you have to specify for the correct layer in the vetor tile layer, not the whole vector tile layer. Make sure to verify the layer name. If it still doesn't, maybe it is better to file an issue at [Leaflet.VectorGrid](https://github.com/Leaflet/Leaflet.VectorGrid).
